apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: knative-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/knative-operator
  prune: true
  wait: true
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: v1
      kind: Namespace
      name: knative-operator
    - apiVersion: apps/v1
      kind: Deployment
      name: knative-operator
      namespace: knative-operator
