apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kserve
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/kserve
  prune: true
  wait: true
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: knative-operator
      namespace: knative-operator
    - apiVersion: operator.knative.dev/v1beta1
      kind: KnativeServing
      name: knative-serving
      namespace: knative-serving
